# Generated by Django 3.2.7 on 2021-09-26 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeoHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='Дата')),
                ('latitude', models.FloatField(verbose_name='Широта')),
                ('longitude', models.FloatField(verbose_name='Долгота')),
                ('accuracy', models.FloatField(verbose_name='Точность')),
                ('altitude', models.FloatField(verbose_name='Высота')),
                ('direction', models.FloatField(verbose_name='Направление')),
                ('speed', models.FloatField(verbose_name='Скорость')),
                ('author', models.TextField(verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Геоданные',
                'verbose_name_plural': 'Геоданные',
            },
        ),
    ]
